//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.29 at 11:57:43 AM CDT 
//


package com.smarsh.dataengineering.model.digxml;

import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionEvent", namespace = "http://dig.apc.xmlns.commons.platform.actiance.com/itm/interaction/transcript/1.0", propOrder = {
    "actionType",
    "actionSubType",
    "actionState",
    "policy",
    "eventTime",
    "actorParticipantIds",
    "assigneeParticipantIds",
    "subject",
    "textContent",
    "attributes"
})
public class ActionEvent {

    @XmlElement(name = "action-type", required = true, namespace = "http://dig.apc.xmlns.commons.platform.actiance.com/itm/interaction/transcript/1.0")
    protected String actionType;
    @XmlElement(name = "action-sub-type", namespace = "http://dig.apc.xmlns.commons.platform.actiance.com/itm/interaction/transcript/1.0")
    protected String actionSubType;
    @XmlElement(name = "action-state", namespace = "http://dig.apc.xmlns.commons.platform.actiance.com/itm/interaction/transcript/1.0")
    protected String actionState;
    @XmlElement(name = "policy", namespace = "http://dig.apc.xmlns.commons.platform.actiance.com/itm/interaction/transcript/1.0")
    protected String policy;
    @XmlElement(name = "event-time", namespace = "http://dig.apc.xmlns.commons.platform.actiance.com/itm/interaction/transcript/1.0")
    protected TimeStamp eventTime;
    @XmlElement(name = "actor-participant-ids", required = true, namespace = "http://dig.apc.xmlns.commons.platform.actiance.com/itm/interaction/transcript/1.0")
    protected ActorParticipantIds actorParticipantIds;
    @XmlElement(name = "assignee-participant-ids", namespace = "http://dig.apc.xmlns.commons.platform.actiance.com/itm/interaction/transcript/1.0")
    protected AssigneeParticipantIds assigneeParticipantIds;
    @XmlElement(namespace = "http://dig.apc.xmlns.commons.platform.actiance.com/itm/interaction/types/1.0")
    protected Subject subject;
    @XmlElement(name = "text-content", namespace = "http://dig.apc.xmlns.commons.platform.actiance.com/itm/interaction/transcript/1.0")
    protected TextContent textContent;
    @XmlElement(namespace = "http://dig.apc.xmlns.commons.platform.actiance.com/itm/interaction/transcript/1.0")
    protected IndexableAttributes attributes;
    @XmlAttribute(name = "action-event-id", required = true)
    protected String actionEventId;
    @XmlAttribute(name = "parent-action-event-id")
    protected String parentActionEventId;
    @XmlAttribute(name = "coc-hash-value")
    protected String cocHashValue;

    public String getActionType() {
        return actionType;
    }

    public void setActionType(String value) {
        this.actionType = value;
    }

    public String getActionSubType() {
        return actionSubType;
    }

    public void setActionSubType(String value) {
        this.actionSubType = value;
    }

    public String getActionState() {
        return actionState;
    }

    public void setActionState(String value) {
        this.actionState = value;
    }

    public String getPolicy() {
        return policy;
    }

    public void setPolicy(String value) {
        this.policy = value;
    }

    public TimeStamp getEventTime() {
        return eventTime;
    }

    public void setEventTime(TimeStamp value) {
        this.eventTime = value;
    }

    public ActorParticipantIds getActorParticipantIds() {
        return actorParticipantIds;
    }

    public void setActorParticipantIds(ActorParticipantIds value) {
        this.actorParticipantIds = value;
    }

    public AssigneeParticipantIds getAssigneeParticipantIds() {
        return assigneeParticipantIds;
    }

    public void setAssigneeParticipantIds(AssigneeParticipantIds value) {
        this.assigneeParticipantIds = value;
    }

    public Subject getSubject() {
        return subject;
    }

    public void setSubject(Subject value) {
        this.subject = value;
    }

    public TextContent getTextContent() {
        return textContent;
    }

    public void setTextContent(TextContent value) {
        this.textContent = value;
    }

    public IndexableAttributes getAttributes() {
        return attributes;
    }

    public void setAttributes(IndexableAttributes value) {
        this.attributes = value;
    }

    public String getActionEventId() {
        return actionEventId;
    }

    public void setActionEventId(String value) {
        this.actionEventId = value;
    }

    public String getParentActionEventId() {
        return parentActionEventId;
    }

    public void setParentActionEventId(String value) {
        this.parentActionEventId = value;
    }

    public String getCocHashValue() {
        return cocHashValue;
    }

    public void setCocHashValue(String value) {
        this.cocHashValue = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "actorParticipantId"
    })
    public static class ActorParticipantIds {

        @XmlElement(name = "actor-participant-id", namespace = "http://dig.apc.xmlns.commons.platform.actiance.com/itm/interaction/transcript/1.0", required = true)
        protected List<String> actorParticipantId;

        public List<String> getActorParticipantId() {
            if (actorParticipantId == null) {
                actorParticipantId = new ArrayList<String>();
            }
            return this.actorParticipantId;
        }

    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "assigneeParticipantId"
    })
    public static class AssigneeParticipantIds {

        @XmlElement(name = "assignee-participant-id", namespace = "http://dig.apc.xmlns.commons.platform.actiance.com/itm/interaction/transcript/1.0", required = true)
        protected List<String> assigneeParticipantId;

        public List<String> getAssigneeParticipantId() {
            if (assigneeParticipantId == null) {
                assigneeParticipantId = new ArrayList<String>();
            }
            return this.assigneeParticipantId;
        }

    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class TextContent {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "content-type")
        protected MimeType contentType;

        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }

        public MimeType getContentType() {
            if (contentType == null) {
                return MimeType.TEXT_PLAIN;
            } else {
                return contentType;
            }
        }

        public void setContentType(MimeType value) {
            this.contentType = value;
        }

    }
}
