//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.29 at 11:57:43 AM CDT 
//


package com.smarsh.dataengineering.model.digxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModalityClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="ModalityClass"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="uc"/&gt;
 *     &lt;enumeration value="email"/&gt;
 *     &lt;enumeration value="collaboration"/&gt;
 *     &lt;enumeration value="social"/&gt;
 *     &lt;enumeration value="file archive"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ModalityClass")
@XmlEnum
public enum ModalityClass {

    @XmlEnumValue("uc")
    UC("uc"),
    @XmlEnumValue("email")
    EMAIL("email"),
    @XmlEnumValue("collaboration")
    COLLABORATION("collaboration"),
    @XmlEnumValue("social")
    SOCIAL("social"),
    @XmlEnumValue("file archive")
    FILE_ARCHIVE("file archive");
    private final String value;

    ModalityClass(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ModalityClass fromValue(String v) {
        for (ModalityClass c: ModalityClass.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
