//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.29 at 11:57:43 AM CDT 
//


package com.smarsh.dataengineering.model.digxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for text-event-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="text-event-type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="normal message"/&gt;
 *     &lt;enumeration value="disclaimer message"/&gt;
 *     &lt;enumeration value="notice message"/&gt;
 *     &lt;enumeration value="warning message"/&gt;
 *     &lt;enumeration value="file transfer message"/&gt;
 *     &lt;enumeration value="participant join message"/&gt;
 *     &lt;enumeration value="participant leave message"/&gt;
 *     &lt;enumeration value="form message"/&gt;
 *     &lt;enumeration value="admin action message"/&gt;
 *     &lt;enumeration value="audio"/&gt;
 *     &lt;enumeration value="video"/&gt;
 *     &lt;enumeration value="meeting"/&gt;
 *     &lt;enumeration value="header"/&gt;
 *     &lt;enumeration value="body"/&gt;
 *     &lt;enumeration value="posting"/&gt;
 *     &lt;enumeration value="comment"/&gt;
 *     &lt;enumeration value="share"/&gt;
 *     &lt;enumeration value="subscribe"/&gt;
 *     &lt;enumeration value="add to"/&gt;
 *     &lt;enumeration value="like"/&gt;
 *     &lt;enumeration value="dislike"/&gt;
 *     &lt;enumeration value="task"/&gt;
 *     &lt;enumeration value="calendar event"/&gt;
 *     &lt;enumeration value="poll posting"/&gt;
 *     &lt;enumeration value="poll response"/&gt;
 *     &lt;enumeration value="profile"/&gt;
 *     &lt;enumeration value="attached text"/&gt;
 *     &lt;enumeration value="other"/&gt;
 *     &lt;enumeration value="social posting"/&gt;
 *     &lt;enumeration value="eml skeleton"/&gt;
 *     &lt;enumeration value="eml journal report"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "text-event-type")
@XmlEnum
public enum TextEventType {

    @XmlEnumValue("normal message")
    NORMAL_MESSAGE("normal message"),
    @XmlEnumValue("disclaimer message")
    DISCLAIMER_MESSAGE("disclaimer message"),
    @XmlEnumValue("notice message")
    NOTICE_MESSAGE("notice message"),
    @XmlEnumValue("warning message")
    WARNING_MESSAGE("warning message"),
    @XmlEnumValue("file transfer message")
    FILE_TRANSFER_MESSAGE("file transfer message"),
    @XmlEnumValue("participant join message")
    PARTICIPANT_JOIN_MESSAGE("participant join message"),
    @XmlEnumValue("participant leave message")
    PARTICIPANT_LEAVE_MESSAGE("participant leave message"),
    @XmlEnumValue("form message")
    FORM_MESSAGE("form message"),
    @XmlEnumValue("admin action message")
    ADMIN_ACTION_MESSAGE("admin action message"),
    @XmlEnumValue("audio")
    AUDIO("audio"),
    @XmlEnumValue("video")
    VIDEO("video"),
    @XmlEnumValue("meeting")
    MEETING("meeting"),
    @XmlEnumValue("header")
    HEADER("header"),
    @XmlEnumValue("body")
    BODY("body"),
    @XmlEnumValue("posting")
    POSTING("posting"),
    @XmlEnumValue("comment")
    COMMENT("comment"),
    @XmlEnumValue("share")
    SHARE("share"),
    @XmlEnumValue("subscribe")
    SUBSCRIBE("subscribe"),
    @XmlEnumValue("add to")
    ADD_TO("add to"),
    @XmlEnumValue("like")
    LIKE("like"),
    @XmlEnumValue("dislike")
    DISLIKE("dislike"),
    @XmlEnumValue("task")
    TASK("task"),
    @XmlEnumValue("calendar event")
    CALENDAR_EVENT("calendar event"),
    @XmlEnumValue("poll posting")
    POLL_POSTING("poll posting"),
    @XmlEnumValue("poll response")
    POLL_RESPONSE("poll response"),
    @XmlEnumValue("profile")
    PROFILE("profile"),
    @XmlEnumValue("attached text")
    ATTACHED_TEXT("attached text"),
    @XmlEnumValue("other")
    OTHER("other"),
    @XmlEnumValue("social posting")
    SOCIAL_POSTING("social posting"),
    @XmlEnumValue("eml skeleton")
    EML_SKELETON("eml skeleton"),
    @XmlEnumValue("eml journal report")
    EML_JOURNAL_REPORT("eml journal report");
    private final String value;

    TextEventType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TextEventType fromValue(String v) {
        for (TextEventType c: TextEventType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
