//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.29 at 11:57:43 AM CDT 
//


package com.smarsh.dataengineering.model.digxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserVisibility.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="UserVisibility"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="always visible"/&gt;
 *     &lt;enumeration value="optionally visible"/&gt;
 *     &lt;enumeration value="hidden"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "UserVisibility")
@XmlEnum
public enum UserVisibility {

    @XmlEnumValue("always visible")
    ALWAYS_VISIBLE("always visible"),
    @XmlEnumValue("optionally visible")
    OPTIONALLY_VISIBLE("optionally visible"),
    @XmlEnumValue("hidden")
    HIDDEN("hidden");
    private final String value;

    UserVisibility(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UserVisibility fromValue(String v) {
        for (UserVisibility c: UserVisibility.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
